server:
  port: 8080

spring:
  Dtp:
    executors:
      # 线程池1
      - poolName: dtpExecutor1
        corePoolSize: 2
        maximumPoolSize: 5
      #...其他参数

#      # 线程池2
#      - poolName: dtpExecutor2
#        corePoolSize: 2
#        maximumPoolSize: 15
